# Generated by Django 4.0.6 on 2022-08-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaJugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('celular', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_torneo', models.IntegerField()),
                ('numero_partido', models.IntegerField()),
                ('ronda', models.IntegerField()),
                ('dni_jugador_1', models.IntegerField()),
                ('dni_jugador_2', models.IntegerField()),
                ('fecha_partido', models.DateField()),
                ('jugador1_ausente', models.BooleanField()),
                ('jugador2_ausente', models.BooleanField()),
                ('jugador1_set_1', models.IntegerField()),
                ('jugador1_set_2', models.IntegerField()),
                ('jugador2_set_1', models.IntegerField()),
                ('jugador2_set_2', models.IntegerField()),
                ('jugador1_Tiebreak', models.IntegerField()),
                ('jugador2_Toebreak', models.IntegerField()),
                ('dni_ganador', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('categoria', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('detalle', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Torneo_Inscriptos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_torneo', models.IntegerField()),
                ('dni_jugador', models.IntegerField()),
            ],
        ),
    ]
