# Generated by Django 4.0.6 on 2022-08-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTorneo', '0002_alter_partidos_jugador1_ausente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidos',
            name='jugador1_Tiebreak',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='partidos',
            name='jugador2_Toebreak',
            field=models.IntegerField(null=True),
        ),
    ]
